---
abstract: 'Prima event loop adapter for AnyEvent'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  AnyEvent::HTTP: '0'
  ExtUtils::MakeMaker: '0'
  Test::HTTP::LocalServer: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: AnyEvent-Impl-Prima
no_index:
  directory:
    - t
    - inc
provides:
  AnyEvent::Impl::Prima:
    file: lib/AnyEvent/Impl/Prima.pm
    version: '0.01'
requires:
  AnyEvent: '0'
  Prima: '1.50'
  perl: '5.010'
resources:
  repository: git://github.com/Corion/anyevent-impl-prima.git
version: '0.01'
x_static_install: 1
